### ISSUE TITLE
Data augmentation for training branchbody.

### ISSUE THREAD

**Issue by anuragdeshmukh** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#15]
Are the tripelets being created by 'create_triplet_ilsvrc_annotations.py' also being used to train the brachbody to extract the appearance features? 

In specific are we using the same augmentations in both logistic regression training and brachbody training?

**Comment by AlbertoSabater** [comment]
Yes. Augmentations can be used in both trainings.
