### ISSUE TITLE
On the idea of algorithm

### ISSUE THREAD

**Issue by csu-qwjy** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#16]
Very amazing work, thank you for the source code. 
I have a question: Only the matching problem can be solved by Location ,geometry and Appearance, but the continuous false detection and the missing detection in a small section can not be solved.

**Comment by AlbertoSabater** [comment]
Continuous false detection cannot be solved. But in practice, REPP solves false detections (mislabeled or low-scoring detections) that happen in frames with many artifacts (blurred, out of focus...).
Missing detections are frequently improved. They are frequently detected but with low scores. REPP boost their score (and label) by analyzing their surrounding frame correspondences.
In general terms, REPP fix different issues generated by the object detector. But at the end the quality of the base detections supposes an important bottleneck. However, if real-time/fast processing is a requirement, a bigger/better object detector can be used on sparse frames along with REPP, i.e. processing all the frames is not always needed.

**Comment by csu-qwjy** [comment]
Thank you very much for your reply. 
False detections (mislabeled or low-scoring detections) is solved by traditional methods，such as Seq-Bbox Matching.
It is not known whether this end-to-end training can affect the confidence of detection?

**Comment by AlbertoSabater** [comment]
The confidence of a detection is given by its class scores. REPP modifies the class scores and thus, the detection confidence. This modification is focused to fix mislabeling and low-scoring detections, and also to lower the confidence of false positives.
