### ISSUE TITLE
normalize output repp

### ISSUE THREAD

**Issue by stu-doc** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#19]
Hello,

Thanks for sharing this nice repo.

I would like normalize output repp for get map with yolo4 program. how i can do it?
output repp xyxy or xywh?

thanks

**Comment by sylivahf** [comment]
hello, i also want to add the post-processing into yolov5's detect.py. but i got the poor predictions. 
did you have the better predictions?

**Comment by AlbertoSabater** [comment]
Hello. I am not familiar with YOLO 4 and 5. 
REPP uses the COCO format (xywh), which eases the later mAP calculation with pycocotools.
