### ISSUE TITLE
Which hyper-parameters are important？

### ISSUE THREAD

**Issue by fxd0122** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#28]
When I used REPP for post-processing, it didn't improve or even worse. I would like to ask if some parameters need to be adjusted? for example distance_func(when I use logreg as the distance function, the performance is very bad. why is this？)， clf_mode....

**Comment by AlbertoSabater** [comment]
Take a look at the [Quick usage guide](https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#quick-usage-guide) and the [paper](https://arxiv.org/abs/2009.11050).
