### ISSUE TITLE
Seq-Bbox-Matching and Seq-NMS implementation

### ISSUE THREAD

**Issue by moshes7** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#3]
It is written in the paper that you have implemented Seq-Bbox-Matching, and used FGFA implementation of Seq-NMS (with parameters from the original paper).
Can you please point me to these implementations in your code?
If you haven't uploaded them, could you do so?

**Comment by AlbertoSabater** [comment]
You can run my implementation of seq-bbox-matching by using REPP.py with `distance_func='def''` and `recoordinate=False`.
The code I used for Seq-NMS can be found [here](https://github.com/msracver/Flow-Guided-Feature-Aggregation/blob/master/lib/nms/seq_nms.py).
