### ISSUE TITLE
Embedding model

### ISSUE THREAD

**Issue by nikk-nikaznan** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#6]
Hi,
 
Thank you for the great work. 
I want to try to implement your work for detection from detectron2. 
Your get_repp_predictions.py really helpful for me to re-format my prediction from detectron2. However, I am stuck in getting the embedding_model. Is there any example on how the embedding model need to look like?  

Thank you

**Comment by AlbertoSabater** [comment]
Hi, thank you for your interest.

I recommend you not using the `embedding_model`. It is very time-consuming to code and train and you can get great results without it. Just set in the [cfg file](https://github.com/AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection/blob/master/REPP_cfg/fgfa_repp_cfg.json) `appearance_matching` to `False`, and then you just have to calculate the rest of the box features related to their size, location, etc. Bbox descriptors are not needed.

**Comment by shardulparab97** [comment]
@AlbertoSabater I am using scaled yolo v4 in my current project.
I have already implemented the version with **appearance_matching** set as False for Scaled Yolo V4 and am getting a good improvement in results. But there are cases of false positives, mixing of different objects in tubelets at times, etc. 
Hence, want to dedicate time to building the **embedding model** for the same.

It would be really great if you could provide an idea/strcuture of the embedding model and the manner in which feature maps are pulled from a base model.

Thank you.
