### ISSUE TITLE
ImageNet VID dataset

### ISSUE THREAD

**Issue by ZiyanZhu1994** [AlbertoSabater/Robust-and-efficient-post-processing-for-video-object-detection#7]
Hi. I am trying to download ImageNet VID dataset from http://www.image-net.org/challenges/LSVRC/2017/2017-downloads. It seems that the download link is down. Could anyone share the ImageNet VID dataset? Many thanks!

**Comment by AlbertoSabater** [comment]
Hi! Check this link: https://bvisionweb1.cs.unc.edu/ILSVRC2017/download-videos-1p39.php

**Comment by ZiyanZhu1994** [comment]
It works! Thank you!
